// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TooliRent.Infrastructure.Data;

#nullable disable

namespace TooliRent.Infrastructure.Migrations
{
    [DbContext(typeof(TooliRentContext))]
    [Migration("20251102004147_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TooliRent.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Elektriska verktyg för byggarbete och hantverk",
                            Name = "Elverktyg"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Traditionella handverktyg för precision och detaljarbete",
                            Name = "Handverktyg"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Verktyg för mätning och märkning",
                            Name = "Mätverktyg"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Skyddsutrustning för säkert arbete",
                            Name = "Säkerhetsutrustning"
                        });
                });

            modelBuilder.Entity("TooliRent.Models.OrderDeatils", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckedOutAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date2Hire")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date2Return")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LateFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToolId");

                    b.HasIndex("UserId");

                    b.ToTable("OrderDeatils");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckedOutAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date2Hire = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date2Return = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LateFee = 0.00m,
                            ReturnedAt = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Returned",
                            ToolId = 2,
                            TotalPrice = 105.00m,
                            UpdatedAt = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("TooliRent.Models.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Bosch",
                            CategoryId = 1,
                            Description = "Professionell slagborrmaskin för betong och murning",
                            IsAvailable = true,
                            Model = "GSB 13 RE",
                            Name = "Slagborrmaskin",
                            PricePerDay = 45.00m,
                            SerialNumber = "BOSCH-001"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Makita",
                            CategoryId = 1,
                            Description = "125mm vinkelslip för kapning och slipning",
                            IsAvailable = true,
                            Model = "GA5030",
                            Name = "Vinkelslip",
                            PricePerDay = 35.00m,
                            SerialNumber = "MAKITA-002"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Festool",
                            CategoryId = 1,
                            Description = "Precisionsticksåg med pendelfunktion",
                            IsAvailable = true,
                            Model = "PS 420 EBQ",
                            Name = "Sticksåg",
                            PricePerDay = 55.00m,
                            SerialNumber = "FESTOOL-003"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Stanley",
                            CategoryId = 2,
                            Description = "Kluvspark 450g med glasfiberhandtag",
                            IsAvailable = true,
                            Model = "STHT0-51309",
                            Name = "Hammare",
                            PricePerDay = 15.00m,
                            SerialNumber = "STANLEY-004"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Wera",
                            CategoryId = 2,
                            Description = "Set med 6 isolerade skruvmejslar",
                            IsAvailable = true,
                            Model = "Kraftform Plus",
                            Name = "Skruvmejselset",
                            PricePerDay = 20.00m,
                            SerialNumber = "WERA-005"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Leica",
                            CategoryId = 3,
                            Description = "Precision laserdistansmätare upp till 100m",
                            IsAvailable = true,
                            Model = "DISTO D2",
                            Name = "Lasermätare",
                            PricePerDay = 40.00m,
                            SerialNumber = "LEICA-006"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Stabila",
                            CategoryId = 3,
                            Description = "Aluminium vattenpass 60cm med 3 libeller",
                            IsAvailable = true,
                            Model = "70-2",
                            Name = "Vattenpass",
                            PricePerDay = 25.00m,
                            SerialNumber = "STABILA-007"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "3M",
                            CategoryId = 4,
                            Description = "Ventilerad skyddshjälm med justerbart huvudband",
                            IsAvailable = true,
                            Model = "SecureFit X5000",
                            Name = "Skyddshjälm",
                            PricePerDay = 10.00m,
                            SerialNumber = "3M-008"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Uvex",
                            CategoryId = 4,
                            Description = "Skyddsglasögon med anti-imma coating",
                            IsAvailable = false,
                            Model = "i-vo",
                            Name = "Skyddsglasögon",
                            PricePerDay = 8.00m,
                            SerialNumber = "UVEX-009"
                        });
                });

            modelBuilder.Entity("TooliRent.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Leon.Johanssonsens@example.com",
                            FirstName = "Leon",
                            LastName = "Johansson",
                            PasswordHash = "Adminpower",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "DoeTheJohn@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "password123",
                            Role = "Member"
                        },
                        new
                        {
                            Id = 3,
                            Email = "StarTrekFan@example.com",
                            FirstName = "Petter",
                            LastName = "Boström",
                            PasswordHash = "Maythe4",
                            Role = "Member"
                        });
                });

            modelBuilder.Entity("TooliRent.Models.OrderDeatils", b =>
                {
                    b.HasOne("TooliRent.Models.Tool", "Tool")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TooliRent.Models.User", "User")
                        .WithMany("OrderDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tool");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TooliRent.Models.Tool", b =>
                {
                    b.HasOne("TooliRent.Models.Category", "Category")
                        .WithMany("Tools")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TooliRent.Models.Category", b =>
                {
                    b.Navigation("Tools");
                });

            modelBuilder.Entity("TooliRent.Models.Tool", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("TooliRent.Models.User", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
